# Generated by Django 2.1.4 on 2019-11-28 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('isbn_number', models.CharField(max_length=13)),
            ],
            options={
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='BudgetCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=50, null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('allocatedAmount', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BudgetExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateRequested', models.DateField(default=django.utils.timezone.now)),
                ('amountRequested', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('approvedAmount', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('reason', models.CharField(max_length=1000)),
                ('status', models.CharField(max_length=20)),
                ('remarks', models.CharField(max_length=1000)),
                ('file', models.FileField(null=True, upload_to='files')),
                ('nowDate', models.DateField()),
                ('category', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='sdrc.BudgetCategory')),
            ],
        ),
        migrations.CreateModel(
            name='FirstVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('user', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=1000)),
                ('issueEncountered', models.CharField(max_length=1000)),
                ('issueDescription', models.CharField(max_length=5000)),
                ('issuePriority', models.CharField(max_length=20)),
                ('dateEncountered', models.DateField()),
                ('issueStatus', models.BooleanField(default=False)),
                ('issueResolution', models.CharField(default='N/A', max_length=1000)),
                ('nowDate', models.DateField()),
                ('file', models.FileField(null=True, upload_to='files')),
            ],
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestoneName', models.CharField(max_length=1000)),
                ('milestonestartDate', models.DateField(blank=True, null=True)),
                ('milestoneendDate', models.DateField(blank=True, null=True)),
                ('milestoneFinished', models.DateField(blank=True, null=True)),
                ('milestoneStatus', models.CharField(default='Not Started', max_length=30)),
                ('trancheAmount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('nowDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_project', models.BooleanField(default=False)),
                ('principal_investigator', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountNumber', models.IntegerField()),
                ('projectTitle', models.CharField(max_length=1000)),
                ('fundingAgency', models.CharField(max_length=1000)),
                ('progress', models.IntegerField(default=0, null=True)),
                ('projectCost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('nowDate', models.DateField()),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('files', models.FileField(blank=True, null=True, upload_to='')),
                ('contractFile', models.FileField(blank=True, null=True, upload_to='files')),
                ('finalReport', models.FileField(blank=True, null=True, upload_to='files')),
                ('dateFinished', models.DateField(blank=True, null=True)),
                ('projectOverview', models.TextField()),
                ('status', models.CharField(default='In Progress', max_length=100)),
                ('dateReceived', models.DateField(null=True)),
                ('budgetSpent', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('budgetRemaining', models.DecimalField(decimal_places=2, default=models.DecimalField(decimal_places=2, max_digits=12), max_digits=20)),
                ('hasTranche', models.BooleanField(default=False, null=True)),
                ('trancheStatus', models.CharField(blank=True, max_length=100, null=True)),
                ('tranche', models.CharField(blank=True, choices=[('First Tranche', 'First Tranche'), ('Second Tranche', 'Second Tranche'), ('Third Tranche', 'Third Tranche'), ('Final Tranche', 'Final Tranche')], max_length=100, null=True)),
                ('trancheAmount', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, null=True)),
                ('totalExpense', models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True)),
                ('remarks', models.CharField(blank=True, max_length=5000, null=True)),
                ('principalInvestigator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('role', models.CharField(max_length=100)),
                ('torNumber', models.IntegerField()),
                ('objectives', models.TextField()),
                ('approveDate', models.DateField(null=True)),
                ('responsibleParty', models.CharField(max_length=200)),
                ('status', models.CharField(blank=True, default='For Review', max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdrc.Project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expenseType', models.CharField(max_length=1000, null=True)),
                ('itemType', models.CharField(max_length=1000, null=True)),
                ('expenseName', models.CharField(max_length=1000, null=True)),
                ('expenseLocation', models.CharField(max_length=1000, null=True)),
                ('expenseQuantity', models.CharField(max_length=10, null=True)),
                ('expenseDescription', models.CharField(max_length=5000, null=True)),
                ('amountRequested', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('currency', models.CharField(max_length=10, null=True)),
                ('expenseAmount', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('expenseTotal', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('expenseDate', models.CharField(max_length=20, null=True)),
                ('fromDate', models.CharField(max_length=20, null=True)),
                ('toDate', models.CharField(max_length=20, null=True)),
                ('expenseReceipt', models.FileField(null=True, upload_to='files')),
                ('destination', models.CharField(max_length=50, null=True)),
                ('mode', models.CharField(max_length=50, null=True)),
                ('times', models.IntegerField(null=True)),
                ('days', models.IntegerField(null=True)),
                ('venue', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(max_length=50, null=True)),
                ('remarks', models.CharField(max_length=1000, null=True)),
                ('nowDate', models.DateField()),
                ('category', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='sdrc.BudgetCategory')),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdrc.Milestone')),
                ('project', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='sdrc.Project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateRequested', models.DateField(null=True)),
                ('approvedDate', models.DateField(null=True)),
                ('reason', models.CharField(max_length=1000, null=True)),
                ('status', models.CharField(max_length=20, null=True)),
                ('remarks', models.CharField(max_length=1000, null=True)),
                ('nowDate', models.DateField(null=True)),
                ('project', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='sdrc.Project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=1000)),
                ('member', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='sdrc.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Reallocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_selected_for_reallocation', models.CharField(max_length=100, null=True)),
                ('category_requested', models.CharField(max_length=100, null=True)),
                ('dateRequested', models.DateField(default=django.utils.timezone.now)),
                ('dateApproved', models.DateField(null=True)),
                ('status', models.CharField(default='For Review', max_length=20)),
                ('remarks', models.CharField(max_length=1000, null=True)),
                ('amountReallocated', models.DecimalField(decimal_places=2, max_digits=20)),
                ('project', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='sdrc.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportTitle', models.CharField(max_length=50)),
                ('datefrom', models.DateField(null=True)),
                ('dateto', models.DateField(null=True)),
                ('nowDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskName', models.CharField(max_length=1000, null=True)),
                ('assignedTo', models.CharField(max_length=30)),
                ('taskstartDate', models.DateField(blank=True, null=True)),
                ('taskendDate', models.DateField(blank=True, null=True)),
                ('taskFinished', models.DateField(blank=True, null=True)),
                ('taskStatus', models.CharField(default='Not Started', max_length=30)),
                ('taskFile', models.FileField(null=True, upload_to='files')),
                ('nowDate', models.DateField(blank=True, null=True)),
                ('milestone', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='sdrc.Milestone')),
                ('project', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='sdrc.Project')),
            ],
        ),
        migrations.AddField(
            model_name='milestone',
            name='project',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='sdrc.Project'),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='milestone',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='sdrc.Milestone'),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='project',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='sdrc.Project'),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='resolvedBy',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='task',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='sdrc.Task'),
        ),
        migrations.AddField(
            model_name='budgetextension',
            name='project',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='sdrc.Project'),
        ),
        migrations.AddField(
            model_name='budgetcategory',
            name='project',
            field=models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='sdrc.Project'),
        ),
    ]
