# Generated by Django 2.1.4 on 2019-12-09 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdrc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetextension',
            name='category',
        ),
    ]
